# Generated by Django 2.2.20 on 2021-05-09 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('user_surname', models.CharField(max_length=20, verbose_name='Surname')),
                ('user_address', models.CharField(max_length=30, verbose_name='Address')),
                ('user_phone', models.IntegerField(serialize=False, verbose_name='Telephone')),
                ('test_id', models.CharField(help_text='Enter your id covid test number', max_length=15, primary_key=True, serialize=False, unique=True)),
                ('user_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
