# Generated by Django 2.2.20 on 2021-05-10 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0005_auto_20210510_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('surname', models.CharField(max_length=255, unique=True, verbose_name='surname')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30, verbose_name='Address')),
                ('phone', models.IntegerField(serialize=False, verbose_name='Telephone')),
                ('age', models.IntegerField()),
                ('idtestnumber', models.CharField(help_text='Enter your id covid test number', max_length=15, primary_key=True, serialize=False, unique=True)),
                ('user_create', models.DateTimeField(auto_now_add=True)),
                ('gender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='covid.Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestCovid',
            fields=[
                ('idtestnumber', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('test_center', models.CharField(max_length=20)),
                ('locate', models.CharField(max_length=20)),
                ('result_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='covid.Result')),
            ],
        ),
        migrations.DeleteModel(
            name='CovidTest',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
