# Generated by Django 2.2.20 on 2021-05-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210510_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='female',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gender',
            name='male',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='negative',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='positive',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
