# Generated by Django 2.2.20 on 2021-05-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20210510_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='female',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='male',
        ),
        migrations.RemoveField(
            model_name='result',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='result',
            name='positive',
        ),
        migrations.AddField(
            model_name='gender',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='result',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
