# Generated by Django 2.2.20 on 2021-05-10 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20210510_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.Gender'),
        ),
    ]
