# Generated by Django 2.2.20 on 2021-05-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0010_auto_20210511_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
