# Generated by Django 2.2.20 on 2021-05-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0012_color_otheruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='static/img'),
        ),
    ]
